control_node:
  ros__parameters:

    # =================================================
    #               与 QT_NODE 通信
    # =================================================

    # --- 发布器 (Publishers) ---
    circuit_status_topic: "circuit_status"
    regulator_status_topic: "voltage_regulator_status"
    system_status_topic: "system_status"

    system_settings_topic: "system_settings"
    regulator_settings_topic: "regulator_settings"
    circuit_settings_topic: "circuit_settings"

    # --- 订阅器 (Subscribers) ---
    regulator_operation_command_topic: "regulator_operation_command"
    clear_alarm_topic: "clear_alarm"

    # --- 服务提供方 (Servers) ---
    regulator_breaker_command_service: "regulator_breaker_command"
    circuit_breaker_command_service: "circuit_breaker_command"

    set_system_settings_service: "set_system_settings"
    set_regulator_settings_service: "set_regulator_settings"
    set_circuit_settings_service: "set_circuit_settings"

    # =================================================
    #               与 RECORD_NODE 通信
    # =================================================
    database_status_topic: "database_status"
    get_system_settings_service: "get_system_settings"
    get_regulator_settings_service: "get_regulator_settings"
    get_circuit_settings_service: "get_circuit_settings"

    # =================================================
    #               与 HARDWARE_NODE 通信
    # =================================================
    hardware_regulator_operation_command_topic: "hardware_regulator_operation_command"
    hardware_clear_alarm_topic: "hardware_clear_alarm"

    hardware_circuit_status_topic: "hardware_circuit_status"
    hardware_regulator_status_topic: "hardware_regulator_status"
    hardware_system_status_topic: "hardware_system_status"

    hardware_circuit_settings_topic: "hardware_circuit_settings"
    hardware_regulator_settings_topic: "hardware_regulator_settings"

    set_hardware_regulator_settings_service: "set_hardware_regulator_settings"
    set_hardware_circuit_settings_service: "set_hardware_circuit_settings"

    hardware_regulator_breaker_command_service: "hardware_regulator_breaker_command"
    hardware_circuit_breaker_command_service: "hardware_circuit_breaker_command"
    hardware_set_control_mode_service: "hardware_set_control_mode"

    plc_command_timeout: 2.0

    # =================================================
    #               与 GLOBAL_NODE 通信 (新增)
    # =================================================
    get_cable_info_batch_service: "/global/cable_manager/get_batch"
    cable_sync_interval_sec: 10
