hardware_node:
  ros__parameters:

    # =================================================
    #               发布器话题名称 (Publishers)
    # =================================================
    hardware_circuit_status_topic: "hardware_circuit_status"
    hardware_regulator_status_topic: "hardware_regulator_status"
    hardware_circuit_settings_topic: "hardware_circuit_settings"
    hardware_regulator_settings_topic: "hardware_regulator_settings"
    hardware_system_status_topic: "hardware_system_status"

    # =================================================
    #               订阅器话题名称 (Subscribers)
    # =================================================
    hardware_regulator_operation_command_topic: "hardware_regulator_operation_command"
    hardware_clear_alarm_topic: "hardware_clear_alarm"

    # =================================================
    #               服务名称 (Services)
    # =================================================
    set_hardware_regulator_settings_service: "set_hardware_regulator_settings"
    set_hardware_circuit_settings_service: "set_hardware_circuit_settings"
    hardware_regulator_breaker_command_service: "hardware_regulator_breaker_command"
    hardware_circuit_breaker_command_service: "hardware_circuit_breaker_command"
    hardware_set_control_mode_service: "hardware_set_control_mode"

    # =================================================
    #               硬件节点特定参数
    # =================================================
    use_mock_driver: false

    # --- 轮询周期 (毫秒) ---
    polling_rate_ms: 100

    # --- 光纤网络延迟适配参数 ---
    tcp_connect_timeout_ms: 200      # 建立 TCP 连接的最长等待时间
    tcp_recv_timeout_ms: 200         # 发送指令后等待回复的最长时间 (光纤通常 <20ms，200ms绝对充足)
    regulator_cmd_timeout_ms: 100    # 高频调压指令安全保护停止时间 (Control Node 50ms下发，这里设150ms防抖)
    service_call_timeout_ms: 400    # 供上层 Control/UI 调用的超时阈值

    # =================================================
    #               TCP 连接配置
    # =================================================
    plc_ip_address: "192.168.2.100"
    plc_port: 502
    temp_monitor_ip_address: "192.168.2.95"
    temp_monitor_port: 3000
